### ISSUE TITLE
How to get darcy-dataset?

### ISSUE THREAD

**Issue by study-cnn-lstm** [neuraloperator/neuraloperator#101]
when I run plot_darcy_flow.py, it returns a error.

FileNotFoundError: [Errno 2] No such file or directory: 'C:/ProgramData/Anaconda3/envs/myenv/Lib/site-packages/neuralop/datasets/data/darcy_train_16.pt'

I want to know how to find this file(darcy_train_16.pt),thank you very much.

**Comment by study-cnn-lstm** [comment]
when I run plot_darcy_flow.py, it exits a error.

FileNotFoundError: [Errno 2] No such file or directory: 'C:/ProgramData/Anaconda3/envs/myenv/Lib/site-packages/neuralop/datasets/data/darcy_train_16.pt'

I want to know how to get this file.Thank you very much,if someone can help to solve this question.

**Comment by study-cnn-lstm** [comment]
![sphx_glr_plot_darcy_flow_001](https://user-images.githubusercontent.com/61778834/223058378-983f231f-39b6-47dd-bbe4-36af9cb5bedc.png)
Hello, I would like to ask where can I find the input dataset for this question?

**Comment by JeanKossaifi** [comment]
Thanks for reporting @study-cnn-lstm - it seems the data isn't included in the release. I should have fixed it in the `uno` branch 96fa11b, which should be merged into main soon.

**Comment by study-cnn-lstm** [comment]
Thank you very much!

**Comment by JeanKossaifi** [comment]
Great, closing as resolved.
