### ISSUE TITLE
Burgers data missing

### ISSUE THREAD

**Issue by abako01** [neuraloperator/neuraloperator#104]
I can see the use of Burgers data in the dataloader, however it is missing from the repo: https://github.com/neuraloperator/neuraloperator/blob/main/neuralop/datasets/burgers.py#L7

Would it be possible to get the data? Also is there an example how FNO was trained on Burgers data as the research paper mentioned?

(I would like to use FNO for 1D problem and would like to compare the how the data looks like in the example 1D Burgers.)

Thanks!

**Comment by JeanKossaifi** [comment]
Hi @abako01, the data should be on the old `master` branch. However, we do not host trained models for now. We have rewritten the codebase in the latest version, we will be adding more examples, but you should be able to adapt the [Darcy Flow example](https://neuraloperator.github.io/neuraloperator/dev/auto_examples/plot_FNO_darcy.html#sphx-glr-auto-examples-plot-fno-darcy-py) to run it on any data.
