### ISSUE TITLE
Confusing about the weights in FactorizedSpectralConv

### ISSUE THREAD

**Issue by zhurz21** [neuraloperator/neuraloperator#108]
Hello, I'm recently exploring the realization of FNO. In the source code of the class _FactorizedSpectralConv_ in neuraloperator/neuralop/models/fno_block.py, where the function _forward_ uses the self.__get_weight(indices + i)_ to get weight parameters, would this cause the same weight parameters to be adopted repeatedly by FNOs in different layers? According to my understanding, the indices should be self.__get_weight(2*indices + i)_ .
Looking forward to your reply.

**Comment by JeanKossaifi** [comment]
Thanks @zhurz21, you're absolutely right! This only affects the case where `joint_factorization=True` (it is `False` by default). 
It is fixed in the `uno` branch which we will be merging soon.
