### ISSUE TITLE
Not compatible with amsgrad option in adam optimizer

### ISSUE THREAD

**Issue by andresfcalvo** [neuraloperator/neuraloperator#111]
I have found an issue with the amsgrad option for Adam. I thought it was my code but found the same error after I ran the examples from the paper. I think it may be related to the lploss but I am unsure.

 error: The size of tensor a () must match the size of tensor b () at non-singleton dimension 4

**Comment by JeanKossaifi** [comment]
Hi @andresfcalvo, could you share a minimal snippet of code to reproduce your issue? 
@zongyi-li have you encountered this issue?

**Comment by andresfcalvo** [comment]
Hi, it looks like it is due to the nature of FNO. The amsgrad option in pytorch does not support different tensor sizes. 

I am using the code from here https://github.com/neuraloperator/neuraloperator/blob/af93f781d5e013f8ba5c52baa547f2ada304ffb0/fourier_2d.py

**Comment by JeanKossaifi** [comment]
This is an old version - did you try with the latest code?

**Comment by andresfcalvo** [comment]
I assume you are talking about https://github.com/neuraloperator/neuraloperator/blob/main/neuralop/models/fno_block.py. If so, I will try it and update on it

**Comment by JeanKossaifi** [comment]
Yes, you could directly try running the example: https://neuraloperator.github.io/neuraloperator/dev/auto_examples/plot_FNO_darcy.html#sphx-glr-auto-examples-plot-fno-darcy-py

**Comment by JeanKossaifi** [comment]
Did it fix your issue?

**Comment by JeanKossaifi** [comment]
Closing as inactive.
