### ISSUE TITLE
Question about factorisation

### ISSUE THREAD

**Issue by cdelavegamartin** [neuraloperator/neuraloperator#112]
Hi,

If I understand correctly, in the original formulation, the weights matrix between the FFT and the iFFT is fully dense respect to the modes (up to the max modes specified) and channels. In the tensorised version is this still the case? If, not, would it be possible to specify which dimensions to decouple (eg treat each channel separately)?

Thanks in advance, and sorry if this is a stupid question, I'm not familiar with tensor factorization

**Comment by cdelavegamartin** [comment]
After digging through the code and properly reading the FNO papers, I think I was wrong, and actually in the vanilla implementation is dense respect to channels, but diagonal respect to the modes?
And with the `separable` flag in the Spectral Convolution implementation (https://github.com/neuraloperator/neuraloperator/blob/main/neuralop/models/spectral_convolution.py) it can be made diagonal respect to the channels as well. Is this correct?

**Comment by scaomath** [comment]
> In the tensorised version is this still the case? If, not, would it be possible to specify which dimensions to decouple (eg treat each channel separately)?

Well, the weight itself is still dense. However, under the assumption of a low-rank weight in the frequency domain, an SVD-like operation is applied to construct the weight.

You can keep track of how the spectral conv does this (use VSCode's Find All References will reveal it clearer) from these few lines:

First you set the SVD to say, Tucker decomposition, 

https://github.com/neuraloperator/neuraloperator/blob/74d51e7433baccad3e6657273256287cc358bcea/neuralop/models/spectral_convolution.py#L266

then Tucker decomposition is elegantly implemented here to confuse amateurs with a general arbitrary implementation up to (48-2) dimension tensors :
https://github.com/neuraloperator/neuraloperator/blob/74d51e7433baccad3e6657273256287cc358bcea/neuralop/models/spectral_convolution.py#L61-L80

Print out the output for a 3D or 4D tensor you will see the idea more clearly.

**Comment by JeanKossaifi** [comment]
Thanks @scaomath for the great answer! Indeed, it corresponds to that paper. The weight is always dense, it is either a full tensor or a tensor in factorized form.

I tried to make the contraction code and variable names as clear as possible to avoid any confusion. However, the factorized version is by construction complex as it involves contracting each factor of the decomposition directly with the input activation tensor. In addition we use einsum combined with opt-einsum to find a good contraction path. This is as you mentioned needed to support inputs of any order.

**Comment by cdelavegamartin** [comment]
Hi,

Thanks a lot to both for clarifying this, I think the part of the factorization is clear.

Regarding my assumption, I expressed myself in a confusing way

> After digging through the code and properly reading the FNO papers, I think I was wrong, and actually in the vanilla implementation is dense respect to channels, but diagonal respect to the modes?

By _dense in channels but diagonal in modes_ I meant that in the contraction operation (disregarding the details of factorization) in 1D for example, is something like:
`bix, iox -> box`
Meaning that the amplitude for the frequency bin at index x in output channel o will be a weighted sum of the amplitudes at index x of all the input channels. But no contribution from other frequency bin amplitudes in either the same input channel or others.
Instead of,
`bix, ioxu -> bou`
Where  the amplitude for the frequency bin at index u in output channel o will be a weighted sum of the amplitudes for all frequency bins (x) of all the input channels (i). (_dense both in channels and modes_)

Thank you for your time, and sorry if this is me just being dumb.
Let me know if it would be better to open a different issue for this question

**Comment by JeanKossaifi** [comment]
@cdelavegamartin The contraction formula you refer to can be explained with the convolution theorem: a global convolution in the spatial domain can be realized in the spectral domain with an element-wise multiplication. The contraction is only along the channels. So the weights are not diagonal but the operation is only element-wise along the spatial dimensions.

**Comment by cdelavegamartin** [comment]
@JeanKossaifi great, that is clear now. 

As a sanity check for myself, regarding then
> And with the separable flag in the Spectral Convolution implementation (https://github.com/neuraloperator/neuraloperator/blob/main/neuralop/models/spectral_convolution.py) it can be made diagonal respect to the channels as well. Is this correct?

This means that with `separable=True` no contraction is done along the channels? That is, the operation is element-wise  both along the spatial dimensions and channels? And this  is why `in_channels==out_channels` is required (https://github.com/neuraloperator/neuraloperator/blob/main/neuralop/models/spectral_convolution.py, line 239-245)

**Comment by JeanKossaifi** [comment]
If `separable=True`, it performs the convolution channel-wise -- a better (longer) name would be depthwise-separable convolution. This is why `in_channels == out_channels`.

**Comment by cdelavegamartin** [comment]
Cool, thanks a lot for the help!
