### ISSUE TITLE
Basic steps for reproducing the FNO-network in pure PyTorch for learning?

### ISSUE THREAD

**Issue by kallegrens** [neuraloperator/neuraloperator#119]
Hello!

This library is great to actually predict and use the network, but to learn to inner workings I would like to reproduce a FNO-network in pure PyTorch for learning purposes. Could anyone be kind enough to give some pseudo-code? I have read the theory / parts of the paper. But feel like I would need some pseudo-code to get started.

Best regards!

**Comment by zongyi-li** [comment]
Here is the pytorch inplementation https://github.com/neuraloperator/neuraloperator/blob/master/fourier_1d.py
The blog may be helpful https://zongyi-li.github.io/blog/2020/fourier-pde/
