### ISSUE TITLE
Error: The size of tensor a (2) must match the size of tensor b (8) at non-singleton dimension 5

### ISSUE THREAD

**Issue by travelguy95** [neuraloperator/neuraloperator#121]
Hi Zongyi:

Thank you for your amazing work. I really want to learn this technology, though I am still a novice.
I am trying to run the file here:
https://github.com/Forbu/fourier_neural_operator_obsolete/blob/master/exemples_paper/fourier_3d_exemple.py

I made the following changes:
1) line 166: TRAIN_PATH = '/content/drive/MyDrive/data/NewFolder/ns_V1e-3_N5000_T50.mat'
2) line 167: TEST_PATH = '/content/drive/MyDrive/data/NewFolder/ns_V1e-3_N5000_T50.mat'
3) line 245: "Adam" replaced with "torch.optim.Adam" (could not find .Adam file)
4) line 303: "out = model(x)" replaced with "out = model(x).view(1, S, S, T)" per issue 61

I am getting this error: 
    441         if weight_decay != 0:
--> 442             device_grads = torch._foreach_add(device_grads, device_params, alpha=weight_decay)
    443 
    444         # Decay the first and second moment running average coefficient

RuntimeError: The size of tensor a (2) must match the size of tensor b (8) at non-singleton dimension 5

I appreciate any help you can give me. Thanks so much! I apologize for the inconvenience.

**Comment by travelguy95** [comment]
Nevermind, I made a bad change. The script is running now!

**Comment by AlessandroGhiotto** [comment]
Hello,
i have an analogous RunTimeError when I try to use cuda device (but no issues when i use cpu device), can I ask how do you have fixed that?

**Comment by MaxGhi8** [comment]
Hello,
i have an analogous RunTimeError when I try to use cuda device (but no issues when i use cpu device), can I ask how do you have fixed that?
