### ISSUE TITLE
Questions on the GRF

### ISSUE THREAD

**Issue by cindyisok** [neuraloperator/neuraloperator#122]
Hi Zongyi,
Thanks for your great job! I am puzzled about the generation of Gaussion random field possibly not your field. For example, how can we get this: sqrt_eig = (size**2)*math.sqrt(2.0)*sigma*((4*(math.pi**2)*(k_x**2 + k_y**2) + tau**2)**(-alpha/2.0))?
 I will be very grateful if any more details could be shared.

**Comment by zongyi-li** [comment]
Thanks for your interest in our work! We use a Matern type kernel as in https://arxiv.org/pdf/2005.10224.pdf (equation 3.3). Hope it can be helpful.

**Comment by cindyisok** [comment]
Thanks, this is very helpful.
