### ISSUE TITLE
FNO

### ISSUE THREAD

**Issue by pogotar** [neuraloperator/neuraloperator#127]
Good morning,
I am interested in your article regarding FNOs but I am not clear on what it means to put the Laplacian in the covariance, in particular it is not clear to me how you implemented the GRF code to generate the data (e.g. for Darcy's problem). I wanted to ask if you had any useful references for studying what Gaussian Random Fields and the KL expansion are. 
Thank you in advance

**Comment by zongyi-li** [comment]
Thanks for your interest in our work! We use a Matern type kernel as in https://arxiv.org/pdf/2005.10224.pdf (equation 3.3). Hope it can be helpful.
