### ISSUE TITLE
Domain padding working incorrectly (with fix)

### ISSUE THREAD

**Issue by itskobold** [neuraloperator/neuraloperator#128]
Good afternoon,

It looks like domain padding is working incorrectly as only one axis in my 2D solution is being padded.
The __init__ function in the DomainPadding class converts the variable domain_padding to a list if it's a float or an int.  However, the pad function itself also does this.
Specifically, the problem appears to be the following lines:

https://github.com/neuraloperator/neuraloperator/blob/acf31d15e69c87322a00862b418d6afa9f5e84f5/neuralop/models/padding.py#L26-L27

And the issue can be fixed by simply removing them.

Attached are two examples made before and after removing the lines.  You can see the non-periodic boundary effects are now modelled accurately with the domain padding fix.

Thanks! :)

![pred_6 - Copy](https://user-images.githubusercontent.com/33371778/235306210-9df2dbe4-8557-450c-a5c0-e54117b5b5e8.gif)

![pred_6](https://user-images.githubusercontent.com/33371778/235306828-0f6655ca-1d7f-4d14-ac89-d9914323c2fc.gif)

**Comment by JeanKossaifi** [comment]
Thanks @itskobold for the great issue - reporting the issue clearly and even proposing a fix, wish they were all like this!
I fixed it and added a unit-test in #130. 

I like your visualization -- would you be willing to add a small [example](https://github.com/neuraloperator/neuraloperator/tree/main/examples) of usage of the padding with that visualization? It would be a great addition! :)

**Comment by itskobold** [comment]
Thanks @JeanKossaifi, that's very much appreciated!

I'm actually just finishing off a paper right now focussing on FNO modelling the 2D linear wave equation.  I talk a bit about domain padding in there and am preparing the figures for that section at the moment.  Would be more than happy to add some examples later this month and next based on these figures once everything else is out of the way :)

If you and your team are interested I'd be more than happy to forward you a pre-publication copy of the paper!
