### ISSUE TITLE
discontinuity in inputs

### ISSUE THREAD

**Issue by travelguy95** [neuraloperator/neuraloperator#129]
Hello! Thank you for this great work.

I have a quick question. I am using fourier_2d_time on some radar images. The radar images are taken every hour EXCEPT for a four-hour window every evening when the radar is turned off. Given that the inputs are discontinuous, it is still possible to, say, use the last 48 hourly images to map to the next 12 hourly images? Thanks!

**Comment by itskobold** [comment]
If you have a reasonable way to model the missing time periods (interpolation would be simplest) then you might be best off doing that as a data pre-processing step before feeding it into the FNO.  I can't remember reading anything yet where FNO has solved problems with missing time data but would love to be proven wrong.

**Comment by zongyi-li** [comment]
So we have an 20-hour data every day. Can we simply take the last 20 (or 40) hours as the input and predict the next 20 hour?

**Comment by travelguy95** [comment]
Thank you for your advice! I will try this out!

> So we have an 20-hour data every day. Can we simply take the last 20 (or 40) hours as the input and predict the next 20 hour?
