### ISSUE TITLE
ERRORs when run "pytest neuralop"

### ISSUE THREAD

**Issue by Nirvanall** [neuraloperator/neuraloperator#131]
I installed neuraloperator after cloning the git repository. But when I run `pytest neuralop,` there are two errors as shown below:

___________________________________ ERROR collecting neuralop/models/tests/test_fno_block.py ____________________________________
/opt/anaconda3/lib/python3.8/site-packages/py/_path/local.py:704: in pyimport
    __import__(modname)
neuralop/__init__.py:3: in <module>
    from .models import TFNO3d, TFNO2d, TFNO1d, TFNO
neuralop/models/__init__.py:1: in <module>
    from .tfno import TFNO, TFNO1d, TFNO2d, TFNO3d
neuralop/models/tfno.py:5: in <module>
    from .spectral_convolution import FactorizedSpectralConv
neuralop/models/spectral_convolution.py:7: in <module>
    tl.set_backend('pytorch')
/opt/anaconda3/lib/python3.8/site-packages/tensorly/backend/__init__.py:335: in set_backend
    backend = cls.load_backend(backend)
/opt/anaconda3/lib/python3.8/site-packages/tensorly/backend/__init__.py:313: in load_backend
    importlib.import_module(f"tensorly.backend.{backend_name}_backend")
/opt/anaconda3/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
/opt/anaconda3/lib/python3.8/site-packages/tensorly/backend/pytorch_backend.py:258: in <module>
    PyTorchBackend.register_method(name, getattr(torch, name))
E   AttributeError: module 'torch' has no attribute 'pi'
___________________________________ ERROR collecting neuralop/tests/test_model_from_config.py ___________________________________
neuralop/tests/test_model_from_config.py:35: in <module>
    out = model(in_data)
/opt/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py:727: in _call_impl
    result = self.forward(*input, **kwargs)
neuralop/models/tfno.py:196: in forward
    x = self.fno_blocks(x, layer_idx)
/opt/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py:727: in _call_impl
    result = self.forward(*input, **kwargs)
neuralop/models/fno_block.py:114: in forward
    x_fno = self.convs(x, index)
/opt/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py:727: in _call_impl
    result = self.forward(*input, **kwargs)
neuralop/models/spectral_convolution.py:322: in forward
    x = torch.fft.rfftn(x.float(), norm=self.fft_norm, dim=fft_dims)
E   AttributeError: 'builtin_function_or_method' object has no attribute 'rfftn'

Is there anyway to solve these errors?

**Comment by JeanKossaifi** [comment]
Thanks for the additional information. It looks like you have an old
version of PyTorch, can you just update to a more recent version of PyTorch
(and maybe Python, though 3.8 should be fine)!

Let me know if this doesn’t resolve the issue!
