### ISSUE TITLE
RuntimeError: The size of tensor a (2) must match the size of tensor b (8) at non-singleton dimension 5

### ISSUE THREAD

**Issue by zmqkf73** [neuraloperator/neuraloperator#133]
Hi!

I have a hard time training Navier Stokes data to FNO model. I am training model using NavierStokes_V1e-3_N5000_T50.mat data at the fourier_3d.py code. But when I train the data, the following error occurs every time... How can slove this error?

![image](https://user-images.githubusercontent.com/123081942/236455463-98f7bac0-b7c2-46b6-9074-70c10e6297e5.png)

  - train_a shape = torch.Size([1000, 64, 64, 10])
  - train_u shape = torch.Size([1000, 64, 64, 40])
  - test_a.shape = torch.Size([200, 64, 64, 10])
  - test_u.shape = torch.Size([200, 64, 64, 40])

I saw a similar issue at https://github.com/neuraloperator/neuraloperator/issues/61. and I changed code. But the error still occur.

````
for ep in range(epochs):
    model.train()
    t1 = default_timer()
    train_mse = 0
    train_l2 = 0
        
    for x, y in train_loader:
        x, y = x.cuda(), y.cuda()

        optimizer.zero_grad()
        out = model(x).view(batch_size, S, S, T) 

        mse = F.mse_loss(out, y, reduction='mean')
        # mse.backward()
        
        y = y_normalizer.decode(y)
        out = y_normalizer.decode(out)
        l2 = myloss(out.view(batch_size, -1), y.view(batch_size, -1))
        l2.backward()

        optimizer.step()
        scheduler.step()
        train_mse += mse.item()
        train_l2 += l2.item()

    model.eval()
    test_l2 = 0.0
    with torch.no_grad():
        for x, y in test_loader:
            x, y = x.cuda(), y.cuda()

            out = model(x).view(batch_size, S, S, T)
            out = y_normalizer.decode(out)
            test_l2 += myloss(out.view(batch_size, -1), y.view(batch_size, -1)).item()

    train_mse /= len(train_loader)
    train_l2 /= ntrain
    test_l2 /= ntest

    t2 = default_timer()
    print(ep, t2-t1, train_mse, train_l2, test_l2)
# torch.save(model, path_model)

pred = torch.zeros(test_u.shape)
index = 0
test_loader = torch.utils.data.DataLoader(torch.utils.data.TensorDataset(test_a, test_u), batch_size=1, shuffle=False)
with torch.no_grad():
    for x, y in test_loader:
        test_l2 = 0
        x, y = x.cuda(), y.cuda()
   
        out = model(x).view(1, S, S, T) <- changed this code ############################################################
        out = y_normalizer.decode(out)
        pred[index] = out

        test_l2 += myloss(out.view(1, -1), y.view(1, -1)).item()
        print(index, test_l2)
        index = index + 1
````

**Comment by MaxGhi8** [comment]
Good morning, may I ask what device you are using? If you are using 'cuda' try changing it to 'cpu'. 
The default pytorch device is cpu so in theory it should be enough to put: `mydevice = torch.device('cpu')` instead of `mydevice = torch.device('cuda' if torch.cuda.is_available() else 'cpu')` and never specify the queue usage, so try commenting out lines `x, y = x.cuda(), y.cuda()` in both the training and evaluation phases. Let me know if this solves the problem.
