### ISSUE TITLE
Poisson dataset

### ISSUE THREAD

**Issue by MaxGhi8** [neuraloperator/neuraloperator#135]
Hello, I have been interested in your work and wanted to ask if you could share the dataset that you used for the Poisson equation. Thank you in advance.

**Comment by zongyi-li** [comment]
Unfortunately we couldn't recover the Poisson equation dataset. However, the darcy equation has a very similar format. It's a 2nd order elliptic equation with an additional coefficient term, and it has been one of the standard dataset of the field. Maybe you can try darcy instead?
