### ISSUE TITLE
rule of thumb for FNO parameters

### ISSUE THREAD

**Issue by travelguy95** [neuraloperator/neuraloperator#136]
Hello! I am using FNO to learn satellite images (10 images input, 10 images output). The original images are 1800 x 3600, but I am only focusing on a 256 x 256 section within each image. Here are my FNO parameters:

ntrain = 813
ntest = 56
modes = 12  
width  = 20   <----- I'm not sure what this represents
batch_size = 2
learning_rate = 0.0005
scheduler_step = 100
scheduler_gamma = 0.5
sub = 1
S = 256 
T_in = 10
T = 10 
step = 1

After a few dozen epochs, the training losses have steadily declined but the testing losses have slightly increased. Does anyone have any advice on adjusting the FNO parameters for improved learning? Any rules of thumb? Thank you!

**Comment by zongyi-li** [comment]
It means the model starts to overfit. In general it suggests we should get more training data and use a simpler model. I suppose the data is time sequence. How many sequences do you have?

width is the channel dimension.

**Comment by travelguy95** [comment]
Thank you for the help! I understand now! I figured out how to make the model simpler. The performance does appear to be improved!
