### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorly'

### ISSUE THREAD

**Issue by alwaysbyx** [neuraloperator/neuraloperator#138]
from neuralop.models import TFNO
Raises error:     import tensorly as tl
ModuleNotFoundError: No module named 'tensorly'

**Comment by MaxGhi8** [comment]
Hello, I don't know how you install the folder but if you use the pip installation then you have to install other useful packages to make the neural operator work. All the required packages is: wandb, ruamel.yaml, configmypy, tensorly, tensorly-torch, opt-einsum, h5py, zarr (you can find this list in the main branch of neural operator in the requirements.txt file). Let me know if this solve your issue.

**Comment by JeanKossaifi** [comment]
You can get the requirements with `pip install -r requirements.txt`
