### ISSUE TITLE
Zero-shot super-resolution (how to test temporal resolution invariance)

### ISSUE THREAD

**Issue by mattiaswiklund99** [neuraloperator/neuraloperator#139]
In the article (https://arxiv.org/pdf/2010.08895.pdf) you write that you train on 64 x 64 x 20 dataset and evaluate on 256 x 256 x 80. Does this mean that you increased your sample rate ("record_steps") with a factor of 4, and then scale the number of time steps to predict accordingly?

And more precisely, how did you test temporal resolution invariance? I've tried to do as I described above: Increase sample rate, increase the number of future steps to predict with the same factor (for example increasing from 40 to 80 if increasing record_steps from 50 to 100), in order to predict the same physical time regardless the temporal resolution.  For the input to the network, I always use the vorticity for the first 10 seconds. That is, if the record_steps is 50, I take the first 10 time steps as input. If I double to 100, I instead take every other value for the first 20 time steps as input to the network, in order to always take the same physical time step as input. However, this procedure does not give satisfactory results compared to testing the spatial resolution invariance. Do you have any idea why?

**Comment by zongyi-li** [comment]
Right, for super resolution, we train the model with low resolution and test it on higher resolution inputs. There is a simple script from the previous implementation https://github.com/neuraloperator/neuraloperator/blob/master/scripts/super_resolution.py
We plan to implement it for the new code base soon.

Based on what you describe, there could be two potential issues
(1) It's good to fix the temporal resolution of the input
(2) the padding may cause issue. It's good to remove the padding.
