### ISSUE TITLE
Number of parameters

### ISSUE THREAD

**Issue by zmqkf73** [neuraloperator/neuraloperator#140]
HI! Thank you for always helping me a lot.
I am training NavierStokes_V1e-3_N5000_T50.mat data at FNO3d model(in master branch code),
and counting the number of parameters there are 3,284,201 parameters.
But, i saw your paper that there are 6,558,537 parameters in same environment.
Why are the number of parameters different...?

Below is a part of the code I used.
```
ntrain = 1000
ntest = 200

modes = 8
width = 20

batch_size = 10
learning_rate = 0.001
epochs = 500
iterations = epochs*(ntrain//batch_size)

sub = 1
S = 64 // sub
T_in = 10
T = 40

model = FNO3d(modes, modes, modes, width).cuda() 
```

**Comment by JeanKossaifi** [comment]
If you mean in term of floating points, are you correctly counting the real
and imaginary parts?

**Comment by zmqkf73** [comment]
I don't know because I didn't check it out.
But I just used this function, and It is distributed code in master branch.
```
def count_params(model):
    c = 0
    for p in list(model.parameters()):
        c += reduce(operator.mul, 
                    list(p.size()+(2,) if p.is_complex() else p.size()))
    return c
```

and I mean, there's a difference here
![image](https://github.com/neuraloperator/neuraloperator/assets/123081942/3de23831-1722-4769-becd-e18fa4820f66)

**Comment by zongyi-li** [comment]
The code might be slightly different compared to the original code used in the paper. It's ok just to use the updated one.

**Comment by zmqkf73** [comment]
Thank you for your answer.
