### ISSUE TITLE
AttributeError: module 'torch' has no attribute 'pi'

### ISSUE THREAD

**Issue by GoostValley** [neuraloperator/neuraloperator#142]
Any clue where this error comes from? My torch version is 1.8 with python 3.8

**Comment by MaxGhi8** [comment]
There isn't pi defined in pythorch, try to replace `torch.pi` with `import math` (at the beginning) and then `math.pi`, or you can use `import numpy as np` and then `np.pi`. Let me know if this solve yuor issue.

**Comment by JeanKossaifi** [comment]
Sounds like you have an old version of PyTorch -- can you check that 1.8 is actually the one being used? Can you update to a newer version?

**Comment by GoostValley** [comment]
> Sounds like you have an old version of PyTorch -- can you check that 1.8 is actually the one being used? Can you update to a newer version?

updating to a newer version works.

**Comment by JeanKossaifi** [comment]
Closing as resolved.
