### ISSUE TITLE
How to access different building blocks API??

### ISSUE THREAD

**Issue by Karn3003** [neuraloperator/neuraloperator#145]
https://neuraloperator.github.io/neuraloperator/dev/modules/api.html#layers

Hi, I am unable to import layers from the Library. Please let me know how do I import it. Thanks

**Comment by JeanKossaifi** [comment]
Can you share how you tried to import the layers?

**Comment by Karn3003** [comment]
Yeah I got it recitified as previously I tried importing using the following command.
from neuralop.models import FactorizedSpectralConv

now following it is working for me.
from neuralop.models.fno_block import FactorizedSpectralConv
