### ISSUE TITLE
Issue in understanding the codebase

### ISSUE THREAD

**Issue by Karn3003** [neuraloperator/neuraloperator#153]
Hi, I was going through the codebase, and in Spectral Convolution I haven't understood the following line of code can you please explain to me what you are trying to do here?

         # upper block (truncate high freq)
        out_fft[:, :, :self.half_n_modes[0], :self.half_n_modes[1]] = self._contract(x[:, :, :self.half_n_modes[0], :self.half_n_modes[1]], 
                                                                              self._get_weight(2*indices), separable=self.separable)
        # Lower block
        out_fft[:, :, -self.half_n_modes[0]:, :self.half_n_modes[1]] = self._contract(x[:, :, -self.half_n_modes[0]:, :self.half_n_modes[1]],
                                                                              self._get_weight(2*indices + 1), separable=self.separable)
                                                                              
                                                                              
 Thanks. Looking for your reply.

**Comment by JeanKossaifi** [comment]
It applies the convolution theorem and performs a contraction of the (truncated) Fourier transform of the input with the learned weights of the spectral convolution. You can refer to the Fourier [neural operator paper](https://arxiv.org/abs/2010.08895) for the details.

**Comment by iSach** [comment]
Hello, 

Why are there two weights of size (..., half_modes, half_modes), and why is it applied to the :k_max/2 and -k_max/2:? I don't understand why not it is like that and not directly ":k_max". What am I missing about the implementation of the (R)FFT?
