### ISSUE TITLE
lifting_channels passed to UNO is not used

### ISSUE THREAD

**Issue by acse-cz220** [neuraloperator/neuraloperator#162]
Thank you for maintaining the library. I noticed that the hyperparameter **lifting_channels** is passed to the UNO model but never used. Only **hidden_channels** is passed to the **Lifting** class. Can you please clarify that?

**Comment by JeanKossaifi** [comment]
That's a good point. This is something we need to do, make lifting and projection more generic and make them both MLPs by default, currently the lifting is just a single linear layer.

**Comment by JeanKossaifi** [comment]
Fixed.
