### ISSUE TITLE
A simpler example ?

### ISSUE THREAD

**Issue by remi-rc** [neuraloperator/neuraloperator#163]
Dear creators of NeuralOperator,

thank you for all the work you put into this library, and for sharing it with everyone ! Really inspiring tool :)

I am interested in using FNO for problems which seem in many ways simpler than the ones you treat in your examples. However, I fail to understand how to tweak your code in order to achieve my own goals.

In the examples you treat, the FNO maps (x0,y0,t) to (x,y,t), whereas in my case, the initial condition is always zero, but the simulation depends on many parameters.

The problem is (a1, a2, a3) --> f(x, y), with a1, a2 and a3 scalars. Using your library, I expect the operator to learn the dependency in these parameters, to avoid having to perform my simulations for values of a2 and a3 higher than the one trained (in the same wave you increase time above the training limit).

In your article, you treat the viscosity as a fixed parameter. But what if every simulation of the training set had a different known viscosity, could it be "learnt" at the same time as the Navier-Stokes operator ?

Minimal example :

    (a1, a2, a3) ==> a1 * cos(a2*x + a3*y)
    a1 in [-1,1]
    a2 in [0, 10]
    a3 in [0, 10]
    x in [0, 1]
    y in [0, 1] 

Is this kind of problem a possible candidate for your library ?

ps:  I was able to find some files related to the burgers equation in the repo, but no example is provided. Is this intended ?

**Comment by JeanKossaifi** [comment]
We now provide some simple examples (https://neuraloperator.github.io/neuraloperator/dev/auto_examples/index.html) and are planning to keep adding more over time.

**Comment by remi-rc** [comment]
Thank you for enriching the example database, I'll stay tuned :)

**Comment by cdelavegamartin** [comment]
Hi, not sure if it will be of any use @remi-rc , but I've been thinking about similar problems, and what you describe,

> In the examples you treat, the FNO maps (x0,y0,t) to (x,y,t), whereas in my case, the initial condition is always zero, but the simulation depends on many parameters.

> The problem is (a1, a2, a3) --> f(x, y), with a1, a2 and a3 scalars. Using your library, I expect the operator to learn the dependency in these parameters, to avoid having to perform my simulations for values of a2 and a3 higher than the one trained (in the same wave you increase time above the training limit).

is not really the use case for neural operators, at least in their vanilla versions, AFAIK. Operators in this context refer to maps between function spaces, specifically states of the system. These states need to be discretised somehow to be able to do computations with them, but are assumed to be good representations of elements of an infinite dimensional function space. In your case, you want to map a finite dimensional vector space (coefficients _a_) to an infinite dimensional space (functions _f(x,y)_ ).

**Comment by Robertboy18** [comment]
The above answer is correct, we want to map an infinite dimensional space to an infinite dimensional space. The problem you are targeting, it might be more appropriate to use a standard regression approach or a neural network specifically designed for parameterized function approximation.
