### ISSUE TITLE
Provide end-to-end examples for NS and Burgers?

### ISSUE THREAD

**Issue by alizma** [neuraloperator/neuraloperator#175]
The ``main`` branch currently only has functioning examples and data for Darcy flow problems, but it seems the old ``master`` branch had examples with NS and Burgers. The corresponding data is missing for these two problems as of 34beeae, though you provide dataloaders and additional scripts. 

Could you please provide the associated data by default or link to where to get it for specific experiments?

**Comment by scaomath** [comment]
The data can be downloaded at the `master` branch `README` link. Though the NS data in the original FNO paper is based on a somewhat not very ideal setup (in terms of numerical PDE), only the viscous term is approximated by Crank–Nicolson but not the dominant convective term which makes the scheme essentially explicit. There are many open-source CFD solvers that have fast solvers for streamfunction-vorticity formulation.
