### ISSUE TITLE
Is 'x' in darcy flow datasets represents permeability factor or forced function?

### ISSUE THREAD

**Issue by Shaoqi-Wang** [neuraloperator/neuraloperator#187]
Sorry to the bother,
I am a little confused about the 'True or False' natural value in darcy datasets. which kind of data pairs do the datasets contains, the coefficient-output pair a-u or forced functions-output pair f-u? I don't know what the 'True or False' or '1 or 0' value represents.

**Comment by JeanKossaifi** [comment]
Do you mean in the small darcy example we included?

**Comment by JeanKossaifi** [comment]
Closing as inactive, feel free to reopen.
