### ISSUE TITLE
Question about out_ft in 1d, 2d models.

### ISSUE THREAD

**Issue by dustin20071** [neuraloperator/neuraloperator#190]
First of all, thank you for providing good articles.
While studying your articles, I have some questions.

In 1d model, it is just importing the front part of self.modes1.
# Multiply relevant Fourier modes
        out_ft = torch.zeros(batchsize, self.out_channels, x.size(-1)//2 + 1,  device=x.device, dtype=torch.cfloat)
        out_ft[:, :, :self.modes1] = self.compl_mul1d(x_ft[:, :, **:self.modes1**], self.weights1)

But, in 2d model, the upper out_ft is importing the front of self.modes1, while the lower out_ft is importing the back of self.modes1.
# Multiply relevant Fourier modes
        out_ft = torch.zeros(batchsize, self.out_channels,  x.size(-2), x.size(-1)//2 + 1, dtype=torch.cfloat, device=x.device)
        out_ft[:, :, :self.modes1, :self.modes2] = \
            self.compl_mul2d(x_ft[:, :, **:self.modes1**, :self.modes2], self.weights1)
        out_ft[:, :, -self.modes1:, :self.modes2] = \
            self.compl_mul2d(x_ft[:, :, **-self.modes1**:, :self.modes2], self.weights2)

Question 1. In the 1d model, only the front part of self.modes1 is imported, but in the 2d model, the front part and the back part of self.modes1 are imported. Why is this difference happening?
           
Question 2. In a 2d model, why does getting the front and getting the back only apply to self.modes1 and not to self.modes2?

**Comment by JeanKossaifi** [comment]
Hi @dustin20071 - this is because of the symmetry of the FFT applied to a real signal.
mode1 applies to the first dimension, modes2 to the second. 

You can have a look at FNO for the generic, N-Dimensional implementation.
