### ISSUE TITLE
Explicityly Handle Higher-dimensional Convolutions

### ISSUE THREAD

**Issue by m4e7** [neuraloperator/neuraloperator#204]
Within the [MLP class](https://github.com/neuraloperator/neuraloperator/blob/f7d07dfe170c9abfeaa5e03b7b73ee90b7b0daac/neuralop/layers/mlp.py#L6), we [get ConvNd](https://github.com/neuraloperator/neuraloperator/blob/f7d07dfe170c9abfeaa5e03b7b73ee90b7b0daac/neuralop/layers/mlp.py#L48) assuming `1 <= N <= 3`.

This may not always be the case, and then when N >= 4, we'll need to explicitly used generalized convolution layers.

see, also: https://github.com/neuraloperator/neuraloperator/pull/186/files#r1290902826

**Comment by Robertboy18** [comment]
This should be closed now! Our code now works with any N - dimensional convolution: )!
