### ISSUE TITLE
Bayesian Inverse Problems

### ISSUE THREAD

**Issue by zouhang0914** [neuraloperator/neuraloperator#207]
Hi, sorry to be a bother.
I want to reproduce the Bayesian inverse problems in "FOURIER NEURAL OPERATOR FOR PARAMETRIC PARTIAL DIFFERENTIAL EQUATIONS".
Could you please provide some related repositories.
thanks!

**Comment by JeanKossaifi** [comment]
Closing as duplicate of #227
