### ISSUE TITLE
NS dataset question

### ISSUE THREAD

**Issue by zmqkf73** [neuraloperator/neuraloperator#216]
Hi,
In the PDE datasets page, the NS dataset(viscosity: 1e-4) has shape of [50, 64, 64, 1000] and for the first index i know this is total time step.
In your code, I saw this comment
> T=40 for V1e-3; T=20 for V1e-4; T=10 for V1e-5;

**Why are you only using 30 time steps despite there being a total of 50 time steps?**

**Comment by JeanKossaifi** [comment]
@zongyi-li

**Comment by zongyi-li** [comment]
This is due to the chaotic nature of the NS equation. For large Reynolds number, the Lyapunov exponents get large and the predictable time interval will be shorter. In general we can only match the statistics of highly chaotic systems.
