### ISSUE TITLE
.\neuraloperator\neuralop\training\callbacks.py error

### ISSUE THREAD

**Issue by lalala753** [neuraloperator/neuraloperator#223]
hello , I find a error , in `.\neuraloperator\neuralop\training\callbacks.py` line 343 `self.state_dict['sample']['y']` do not have `sample` , and I find it when run `\neuraloperator\examples\plot_FNO_darcy.py`

**Comment by JeanKossaifi** [comment]
Hi @lalala753 - thanks for reporting. We are updating our trainer class and are in the process of updating the example, this should be fixed shortly. @dhpitt

**Comment by dhpitt** [comment]
Fixed.

**Comment by JeanKossaifi** [comment]
Closing as resolved.
