### ISSUE TITLE
OutputEncoderCallback problem

### ISSUE THREAD

**Issue by Adzej93** [neuraloperator/neuraloperator#226]
Hi, when I tried to run the example (TFNO on Darcy-Flow) through the Colab, I encountered the following problem:
ImportError: cannot import name 'OutputEncoderCallback' from 'neuralop.training' (/usr/local/lib/python3.10/dist-packages/neuralop/training/__init__.py)
Best regards, 
AO

**Comment by JeanKossaifi** [comment]
Are you using the version for pypi? We just updated the examples, you need
the latest version from GitHub for this.

**Comment by Adzej93** [comment]
The update fixed the problem. Thanks!

**Comment by JeanKossaifi** [comment]
Glad to hear, closing as resolved.
