### ISSUE TITLE
Inverse Problem in FNO

### ISSUE THREAD

**Issue by zouhang0914** [neuraloperator/neuraloperator#227]
Hi, I just want to study the Bayesian inverse problems in FNO. Could you please provide some related repositories or some demo cases for me? Thanks a lot!
e-mail: zouhang0914@163.com

**Comment by JeanKossaifi** [comment]
You can have a look at the documentation for some examples of neuralop models https://neuraloperator.github.io/neuraloperator/dev/index.html

For inverse problems, please refer directly to the papers, we don't (yet) have examples for this.

**Comment by JeanKossaifi** [comment]
@zongyi-li for the original paper
