### ISSUE TITLE
import error in Training a TFNO on Darcy-Flow example

### ISSUE THREAD

**Issue by drgona** [neuraloperator/neuraloperator#246]
There seems to be import error issue with the example in [Training a TFNO on Darcy-Flow](https://neuraloperator.github.io/neuraloperator/dev/auto_examples/plot_FNO_darcy.html#sphx-glr-auto-examples-plot-fno-darcy-py)

Error message:

` from neuralop.training import OutputEncoderCallback
ImportError: cannot import name 'OutputEncoderCallback' from 'neuralop.training'
`

I installed the library using `pip install neuraloperator`

The installation and examples seem to work correctly with a manual install.

**Comment by JeanKossaifi** [comment]
Hi @drgona - indeed, the examples on the website are for the latest version of the library. 
We are planning a release soon.
