### ISSUE TITLE
Training the neural operator in 3D spatial domain

### ISSUE THREAD

**Issue by shashikant193** [neuraloperator/neuraloperator#255]
I am trying to train a neural operator model in 3D cartesian space.  Specifically, I aim to learn the operator O: f -> g where f and g are scalar fields and are defined in the domain of R^3.

I couldn't locate any examples that address this specific 3D scalar field to the 3D scalar field problem. Could you please point me to any relevant examples or references?

**Comment by MaxGhi8** [comment]
I do not think that in the original paper where they introduce FNO there are examples with a three-dimensional spatial domain. But there is an example involving Navier-Stokes problem with time and 2D space domain. So if you want some example I suggest you to see in the 'master' branch of this repository and see about the file 'fourier_2d_time.py'.  They even implement the file 'fourier_3d.py' but I don't know if there is any example about that. Anyways it is very very similar to 'fourier_2d.py' where there are a lot of examples. 
Consider that the number of parameters increases exponentially with the size of the problem's domain, so depending on your dataset and how you set the hyperparameters of the neural operator, you may incur long training times. You may consider to use Factorized FNO where the number of parameters increasing only linearly with the dimension of the problem's domain.

I hope this was helpful, I am happy to answer if you have any further questions.

**Comment by Robertboy18** [comment]
@shashikant193 One can now easily solve any n-dimensional FNO problem with the new codebase by passing in , regarding the above comment I do agree that factorized FNO would be a better choice if you are limited by GPU resources.

**Comment by JeanKossaifi** [comment]
@shashikant193 to use a 3D FNO for instance, simply use the FNO, e.g. for keeping 3, 4 and 5 modes:
```python
model = FNO(n_modes=(3, 4, 5), hidden_channels=64, ...)
```

You could also use FNO3d directly but the above is more versatile.

See [documentation](https://neuraloperator.github.io/neuraloperator/dev/modules/generated/neuralop.models.FNO.html#neuralop.models.FNO)
for more details.
