### ISSUE TITLE
Reproducing the published results

### ISSUE THREAD

**Issue by stefanozampini** [neuraloperator/neuraloperator#264]
I would like to know which data should I use to reproduce the results in Table 4, first column (nu = 1.e-3, T=50, N=1000) of ref https://www.jmlr.org/papers/volume24/21-1524/21-1524.pdf. By looking at https://drive.google.com/drive/folders/1UnbQh2WWc6knEHbLn-ZaXrKUZhp7pjt- , I presume I have to use `NavierStokes_V1e-3_N5000_T50` and split the dataset in 1000 train and 4000 test elements. Is that correct?
Also, I noticed in `master` for `fourier_3d.py` you have added an MLP layer and removed the batch-norm. is that the same network configuration used in the above paper?

**Comment by zongyi-li** [comment]
Sorry for the delay. In the paper we used 1000 for training and next 1000 for test. In original paper we didn't have MLP, it is added for better performance.
