### ISSUE TITLE
U-NO on Darcy-Flow (Gallery of example) don't run on cuda

### ISSUE THREAD

**Issue by jinguman** [neuraloperator/neuraloperator#279]
Hello,

U-NO on Darcy-Flow example(Homepage>Gallery of examples) don't run on device=cuda.

Error messages list below.

> 
> RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor
> 

I think that the following sentence needs to be added.
"data_processor = data_processor.to(device)"

Thanks.

**Comment by dhpitt** [comment]
Hi @jinguman , the examples are written to run on cpu.
