### ISSUE TITLE
[Request] Dataset creation and acquisiton documentation

### ISSUE THREAD

**Issue by JoeMWatson** [neuraloperator/neuraloperator#280]
Hi, 

The current examples look nice, but rely on having a preloaded dataset file. It would be good if there was an example that showed how to translate a given PDE into the required dataset format and some best practice on preprocessing for the model. 

The scripts (at least navier stokes) also seem to assume the dataset ready but there is no documentation of how to get this. 
The script `train_navier_stokes.py` returns
`FileNotFoundError: [Errno 2] No such file or directory: '/data/navier_stokes/nsforcing_128_train.pt'`

**Comment by Hrrsmjd** [comment]
You can download some datasets from https://github.com/pdebench/PDEBench or https://huggingface.co/pdearena

**Comment by RanieryMendes** [comment]
Hi, 

I'm facing a similar issue to @JoeMWatson. I would like to kindly request access or directions to the data used for the experiments reported in Li et. al FNO [paper ](https://arxiv.org/abs/2010.08895).

**Comment by dhpitt** [comment]
The  data is provided in `neuralop.data.datasets` as of #299.
