### ISSUE TITLE
coordinates in the darcy flow example

### ISSUE THREAD

**Issue by gokhalen** [neuraloperator/neuraloperator#281]
In the Darcy flow example - 

[https://github.com/neuraloperator/neuraloperator/blob/main/examples/plot_FNO_darcy.py](https://github.com/neuraloperator/neuraloperator/blob/main/examples/plot_FNO_darcy.py
)

Is it correct to think that the coordinates are used as features for the FNO? Do they serve any other purpose?

-Nachiket

**Comment by MaxGhi8** [comment]
I think you are right, you can find a reference on page 12, `preprocessing` section, of the following article [Neural Operator: Learning Maps Between Function Spaces](https://arxiv.org/abs/2108.08481).

let me know if this can answer your question.

Max

**Comment by gokhalen** [comment]
Thanks, that answers it.
