### ISSUE TITLE
Question about differentiation

### ISSUE THREAD

**Issue by gokhalen** [neuraloperator/neuraloperator#283]
I have been reading your paper "[Physics-Informed Neural Operator for Learning Partial Differential Equations](https://arxiv.org/pdf/2111.03794.pdf)". It seems that in equations (14) and (15) in your paper, in which you compute the derivative $u'(x)$ you do not go back recursively to the first Fourier layer i.e. $v_1$. In equation (14) you  stop at $v_{L-1}$ and in equation (15)  you stop at $v_L$.  I just wanted to make sure that I'm not missing anything in my understanding.

**Comment by dhpitt** [comment]
My understanding is that these equations are just describing values at one layer in terms of values at the previous layer.

**Comment by gokhalen** [comment]
Yes, you are correct David. It took me a while to understand that point. I think the goal of those equations is to get the spatial derivatives without giving co-ordinates explicitly as the input to the neural network, as is done with PINNs. And by using the FFT one can get the spatial derivative on the entire grid efficiently.

**Comment by dhpitt** [comment]
Closing, it seems like this is resolved
