### ISSUE TITLE
Passing parameters to the FNO

### ISSUE THREAD

**Issue by Luca-DTU** [neuraloperator/neuraloperator#298]
Hi,
I am struggling to find examples in the documentation of how to pass parameters through to the FNO, for example if I have a dataset with some initial conditions (N,1,res,res) and want to learn a parametric operator where there are one or more parameters so that the FNO also generalises upon variation of the parameters, what is the correct way to pass the parameters through?

What I am doing right now is to have an input of shape (N,1+n_params,res,res) where each parameter is represented by a constant valued (res,res) matrix but it seems very wasteful and inefficient.

Thanks in advance for the help:)

**Comment by dhpitt** [comment]
Hi @Luca-DTU, as of right now I'm not aware of any other way to pass parameters.
