### ISSUE TITLE
Support for irregular meshes.

### ISSUE THREAD

**Issue by profPlum** [neuraloperator/neuraloperator#300]
Hi, I'm confused because FNO is advertised as being discretization invariant. But it still expects rectangular meshes. What would happen if you had a prime number of grid cells & an irregular mesh? Then there would be no exact way to put this into a rectangular mesh for the FNO. Not to mention that even if it could be put into a rectangular format exactly & you just specified irregular positional encodings to deal with irregular mesh. The Fourier Transform still wouldn't "see" the points in a spatially correct way, we would just be passing true spatial positions as a positional encoding and hoping that the network would learn to compensate...

Please correct me if my assumptions are wrong about how this library works.
I'm inferring the lack of support from the darcy flow example, but I could be wrong.

P.S. I've attached an example irregular mesh that I though this library could handle:
<img width="631" alt="image" src="https://github.com/neuraloperator/neuraloperator/assets/4739054/5db6036b-db12-4dd1-a1f9-2c9d79d7de06">

**UPDATE:** I just checked and it seems that there is a paper which created a [new kind of FNO which can handle irregular meshes](https://arxiv.org/pdf/2207.05209.pdf) perhaps considering integrating it into the library.

**Comment by dhpitt** [comment]
Hi @profPlum, you're right that the base FNO isn't designed to handle irregular meshes. However, there are models like the one in the paper you linked (for instance, one that consists of a learned deformation/integral transform into an FNO into another learned deformation layer) that do support irregular meshes. We aren't planning on integrating those models in the next round of updates but stay tuned!

**Comment by dhpitt** [comment]
Hi @profPlum , in our latest round of updates we now expose the `GINO` model to map between irregular meshes.
