### ISSUE TITLE
Problem with lowrank2d_time

### ISSUE THREAD

**Issue by rochaie** [neuraloperator/neuraloperator#302]
Predicting the occurrence of NAN while running the NS equation experiment using the 'lowrank2d_time.py' code, although adjusting it can solve this problem, the predictive performance is not as good as NN, why? Can you explain it?thank you

**Comment by dhpitt** [comment]
Hi @rochaie, is this issue related to the `neuralop` library? If not this might be better suited for an issue in the repo which contains the source mentioned here

**Comment by dhpitt** [comment]
Closing because this is stale and doesn't refer to the current library code
