### ISSUE TITLE
Missing 'burgers.npz' file while training FNO on Burgers` problems  

### ISSUE THREAD

**Issue by srinathdama** [neuraloperator/neuraloperator#309]
When I try to run ```train_burgers.py```, I get the following error as the file ```burgers.npz``` is missing.

```
###############################
Traceback (most recent call last):
  File "/home/neuraloperator/scripts/train_burgers.py", line 74, in <module>
    train_loader, test_loaders, output_encoder = load_burgers_1dtime(data_path=config.data.folder,
  File "/home/neuraloperator/neuralop/datasets/burgers.py", line 52, in load_burgers_1dtime
    with np.load(data_path) as data:
  File "/home/miniconda3/envs/TNO/lib/python3.10/site-packages/numpy/lib/npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/data/burgers/burgers.npz'
```

I could not find ```burgers.npz``` in ```neuralop/datasets/data/```. I would appreciate it if someone could help me access it.    

Thanks in advance!

**Comment by dhpitt** [comment]
Hi @srinathdama, you are correct that we haven't yet released our data file for the 1d Burger's equation. This may change in the future, but for now check out the datasets available on [PDEBench](https://darus.uni-stuttgart.de/dataset.xhtml?persistentId=doi:10.18419/darus-2986)

**Comment by dhpitt** [comment]
#299 will add a low-resolution (16 spatial x 17 temporal) version of the dataset to `Burgers1DTimeDataset`. The full dataset should still be downloaded from PDEBench.
