### ISSUE TITLE
modernized examples 

### ISSUE THREAD

**Issue by gokhalen** [neuraloperator/neuraloperator#315]
Are there modernized examples for the old examples in 

https://github.com/neuraloperator/neuraloperator/tree/master

Thanks,

Nachiket

**Comment by dhpitt** [comment]
Can you be more specific? The example scripts in `scripts` are up to date.

**Comment by gokhalen** [comment]
Sorry, my mistake. I didn't look in `scripts` , just looked in `examples`.
