### ISSUE TITLE
amount of RAM needed for a model to run

### ISSUE THREAD

**Issue by gokhalen** [neuraloperator/neuraloperator#318]
Is there a function to determine how much amount of RAM a model needs to run? 

There is `count_model_params`

https://github.com/neuraloperator/neuraloperator/blob/ae6bdb948b1733a8c1bb862de8127c55c97e3074/neuralop/utils.py#L75

But I suspect the model needs much more memory than just the parameters because it lifts to a higher dimensional space, etc.

Thanks,

Nachiket

**Comment by zongyi-li** [comment]
Beside the number of parameter, the major memory consumption is on the tensor (B, C, W, H) for example, a 128x128 input with channel 32 and batch 20 will be (20x32x128x128). If it goes out of memory, you can either use a smaller batch, smaller channel dim, or smaller resolution.
