### ISSUE TITLE
How to get or create other dataset

### ISSUE THREAD

**Issue by dhleeids** [neuraloperator/neuraloperator#340]
Hi, I would like to experiment with your github for my research.
I want to test FNO using various datasets & various resolutions. (In particular, navier-stokes) 
But this git only offers burgers and darcy in specific resolutions.
Do you have any plans to provide other datasets or data generation code?
If not, I would like to utilize the existing data generation code on the fno github, but it is geared towards pytorch1.6, which makes it difficult to utilize.
If you have a better way to generate another dataset if possible, I'd love to hear about it.
Thank you

**Comment by dhpitt** [comment]
Hi @dhleeids , thanks for opening this issue. We are in the process of adding more data (specifically including Navier-Stokes) and creating an API to download it from Zenodo in PR #299 .

**Comment by dhleeids** [comment]
Thank you for your answer.
 I will try to utilize PR #299 and the code given.
