### ISSUE TITLE
The user guide is too old

### ISSUE THREAD

**Issue by oncogener** [neuraloperator/neuraloperator#377]
I tried to read the user guide, but found that many functions do not exist, can you provide a new user guide, or different versions of the modification instructions

such as from neuralop.models.spectral_convolution import FactorizedSpectralConv
from neuralop.data.datasets import load_darcy_flow_small

**Comment by arcturusannamalai** [comment]
User guide doesn't agree with release docs as mentioned in another issue. Perhaps a versioned user guide is what we need ?

**Comment by dhpitt** [comment]
Hi @James-F1dev , 0.3.0 is not the most current version of neuraloperator - please retry with the new 1.0.0 release!

**Comment by JeanKossaifi** [comment]
Closing as updated in 1.0.0
