### ISSUE TITLE
ModuleNotFoundError: No module named 'wandb'

### ISSUE THREAD

**Issue by kaizenlabs** [neuraloperator/neuraloperator#379]
Hi, looking at your documentation, your python package seems to either be out of date or improperly packaged. 

**Steps to Reproduce**

1. Open at new Python notebook at https://colab.research.google.com/
2. !pip install neuraloperator (according to your documentation at https://neuraloperator.github.io/neuraloperator/dev/index.html)
3. Run the following example in the first cell to observer the error:

`from neuralop.models import FNO

operator = FNO(n_modes=(16, 16), hidden_channels=64,
                in_channels=3, out_channels=1)`

`ModuleNotFoundError: No module named 'wandb'`

You can't just 'pip install wandb' either because it will then throw other errors.

**Comment by kaizenlabs** [comment]
Another simple example that doesn't work. Code is broken in many places. 

<img width="1366" alt="Screenshot 2024-07-24 at 2 47 23 PM" src="https://github.com/user-attachments/assets/4c7c75f8-b7c8-489e-b795-b73834251a9f">

**Comment by dhpitt** [comment]
Hi @kaizenlabs are you building the library from source or installing the PyPI release 0.3.0?

**Comment by dhpitt** [comment]
If installing from PyPI there are additional requirements that need to be installed in the library's current state

**Comment by dhpitt** [comment]
> Another copy/pasted example from the documentation that doesn't work. Code is broken in many places, this one is coming from `darcy.py`.
This is old code built from neuralop v0.3.0 on PyPI. Please try installing from source to see if your issue persists.

**Comment by dhpitt** [comment]
#385 makes `wandb` an optional dependency. Let us know if the issue persists!
