### ISSUE TITLE
Einsum error using separable Fourier convolution 

### ISSUE THREAD

**Issue by HenrikAsmuth** [neuraloperator/neuraloperator#382]
Hi,

There seems to be an issue in the tensor contraction when using the separable Fourier convolution option (`separable=True`).
The problem occurred when I tested the `plot_FNO_darcy.py` example with Tucker contraction as well as in my own toy project. 
Seems like the Einstein summation is not correctly set.

Below, I only pasted the part of the stacktrace which I deemed most relevant. The full error should be reproducible when adding the above option to the model init in the example.

`Traceback (most recent call last):
  File "C:\Users\Henrik\virtual_environments\neuraloperator\venv\lib\site-packages\tensorly\plugins.py", line 72, in cached_einsum
    expression = OPT_EINSUM_PATH_CACHE[key]
KeyError: 'abcd,fghi,bf,eg,ch,di->aecd,(32, 32, 9, 9),(20, 10, 6),(32, 20),(16, 10),(9, 6)'`
...

` File "C:\Users\Henrik\virtual_environments\venv_pytorch\lib\site-packages\opt_einsum\parser.py", line 354, in parse_einsum_input
    raise ValueError("Number of einsum subscripts must be equal to the " "number of operands.")
ValueError: Number of einsum subscripts must be equal to the number of operands.`

**Comment by dhpitt** [comment]
Hi @HenrikAsmuth , thanks for this issue. When I've seen this error in the past, it's been because the shape of the input is not correct. What input shape are you using in your forward pass?

**Comment by dhpitt** [comment]
Hi @HenrikAsmuth , i looked into this this morning and found a bug in `SpectralConv` that is fixed by #389 . Thank you so much for bringing this to our attention!

**Comment by HenrikAsmuth** [comment]
Thank Dave for the quick fix. Will test it asap once it's merged.

**Comment by dhpitt** [comment]
Merged #389
