### ISSUE TITLE
Benchmark 

### ISSUE THREAD

**Issue by Joao97ribeiro** [neuraloperator/neuraloperator#39]
Hi Zongyi Li,
Incredible work, very interesting! 

I am studying this subject in my PhD.
But I am having some difficulty in obtaining the same results as figure 2 of the article (benchmark).
Do you have the codes of the other models that you used to compare with the FNO available?

Thank you,
Joao

**Comment by zongyi-li** [comment]
Figure 2 in the paper seems to be the architecture. Do you mean the experiments on Burgers, Darcy, or Navier-Stokes?

**Comment by zongyi-li** [comment]
Sorry, do you mean you cannot reproduce the results of FNO on any of these datasets? or do you want to test with the baseline methods?

**Comment by Joao97ribeiro** [comment]
I already reproduce for the FNO! I would like to reproduce for the other methods, such as NN, FCN, PCAMM, RBM and LNO. Do you have this code available, for example for the 2-d Darcy Flow equation?

My goal is to obtain the results from table 4 for the different methods. Thanks

**Comment by zongyi-li** [comment]
Oh I see, I see. We haven't decided to publish all the baseline methods, since they need a lot of clean-up. But if you don't mind, I can send you some of these baselines we have at hand. If that can be helpful, please let me know your email address. Thanks.

**Comment by Joao97ribeiro** [comment]
I understand perfectly, so if you don't mind, I would ask you to send it. I'm sure that it will help me. Very grateful for your help, Zongyi. My email is: jp.ar@hotmail.com. Thanks!

**Comment by zongyi-li** [comment]
While I am preparing the code, please see these repositories:

- For GKN and MKGN: https://github.com/zongyi-li/graph-pde 
- For UNets, Resnets, TF-Nets: https://github.com/Rose-STL-Lab/Turbulent-Flow-Net
- The lowrank method is contained in this repostory (e.g. lowrank_2d.py)

I when send you the code for FCN, PCANN, and ROM once I gather them. Thanks!

**Comment by Joao97ribeiro** [comment]
Thank you very much! I am already analyzing the repositories you sent.
Then when you get the code for FCN, PCANN, and RBM, please send. Thanks, Zongyi!

**Comment by kaichang01** [comment]
Hi Zongyi!

I am trying to reproduce the results right now. If you don't mind, is it possible for you to send a copy of the code for the baseline results as well (if you had it)? That would be really helpful!

Best,
Kai

**Comment by kylematoba** [comment]
Same here, would appreciate a copy of the code to replicate the benchmarks to kyle.matoba@epfl.ch. Thanks!

**Comment by JeanKossaifi** [comment]
Closing as inactive. Feel free to reopen.
