### ISSUE TITLE
Unable to locate train.txt File for train_car_cfd.py

### ISSUE THREAD

**Issue by ehsanngh** [neuraloperator/neuraloperator#428]
Hello,

I'm trying to familiarize myself with training the GINO architecture using the provided example for car-CFD. However, I'm having issues locating all the necessary files to run the code. I found some data at this link: https://drive.google.com/drive/folders/1PMuOGUO2A9rzAP3YM8ra3v8ybE8X9foh

However, when I try to run `train_car_cfd.py`, I encounter the following error:
```
Traceback (most recent call last):
  File ".../neuraloperator/scripts/train_car_cfd.py", line 52, in <module>
    data_module = MeshDataModule(config.data.path, 
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../neuraloperator/neuralop/data/datasets/mesh_datamodule.py", line 57, in __init__
    with open(root_dir / "train.txt") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '.../data/car_cfd/train.txt'
```

I'm not sure what the `train.txt` file should contain.

I also attempted to run the older version of the code provided with the paper, available at this link:
https://openreview.net/attachment?id=86dXbqT5Ua&name=supplementary_material

However, I encountered difficulties in building the appropriate dependencies to run that version of the code. I would greatly appreciate any instructions you could provide on how to successfully run the training script for car-CFD.

Thank you!

**Comment by dhpitt** [comment]
Hi @ehsanngh , sorry for the delay in responding. If you download our `CarCFDDataset` from `neuralop.data.datasets.car_cfd_dataset` the files should now be present.

**Comment by ehsanngh** [comment]
@dhpitt Thanks for letting me know! I appreciate the update.

**Comment by ehsanngh** [comment]
@dhpitt Thanks for letting me know. I appreciate the update!
