### ISSUE TITLE
can't run plot_FNO_darcy example

### ISSUE THREAD

**Issue by Penido-exe** [neuraloperator/neuraloperator#440]
When I try to run the example plot_FNO_darcy.py, I get the following error:

```
Traceback (most recent call last):
  File "/home/penido/Documents/ml/repos/neuraloperator/examples/plot_FNO_darcy.py", line 28, in <module>
    train_loader, test_loaders, data_processor = load_darcy_flow_small(
  File "/home/penido/miniconda3/envs/neural_op/lib/python3.9/site-packages/tensorly/utils/deprecation.py", line 100, in wrapped
    f"{deprecated_name} is deprecated, use {use_instead.__name__} instead."
AttributeError: 'str' object has no attribute '__name__'
```

I installed all the requirements via the GitHub repository.

**Comment by JeanKossaifi** [comment]
Are you using the latest version of neuraloperator? Can you check your installed versions?
The [examples](https://neuraloperator.github.io/dev/auto_examples/index.html) are actually executed dynamically in the CI at each new push.

**Comment by JeanKossaifi** [comment]
Closing as inactive - feel free to reopen if this is still an issue.
