### ISSUE TITLE
The simple darcy dataset example seems depracated.

### ISSUE THREAD

**Issue by Onlyartist9** [neuraloperator/neuraloperator#450]
A lot of the methods and classes depicted in the example don't seem available. GridEmbeddings2D for example.

**Comment by dhpitt** [comment]
Hi @Onlyartist9 , thank you for raising this issue. Did you install the library by building from the Git repo, or did you install via pip? The pip build lags behind our most recent source on GitHub by a fair amount (although we're working on fixing that!)

**Comment by Onlyartist9** [comment]
@dhpitt I used the pip build. Thanks for letting me know.
