### ISSUE TITLE
potential bug in the code

### ISSUE THREAD

**Issue by AtiehAlipour-NOAA** [neuraloperator/neuraloperator#476]
Hi, yesterday I was trying to install the package, but was getting an error because of this:

![image](https://github.com/user-attachments/assets/298c1ff5-f1ec-400b-a969-850351b2c8af)

I removed the equal sign, and that solved my issue.

**Comment by JeanKossaifi** [comment]
What is your Python version? My guess is that you are using a fairly old version of Python: this is correct Python syntax that was introduce in 3.8, which has already reached its [end of life](https://devguide.python.org/versions/).

I strongly advise updating to a newer version of Python.

Feel free to reopen if this doesn't fix it.
