### ISSUE TITLE
Can we have GINO use examples? 

### ISSUE THREAD

**Issue by alwaysbyx** [neuraloperator/neuraloperator#479]
Can we have GINO use examples? Hope we will have GINO use examples so we can know bettet how to use it. 
Specifically, I dont know how to transform input (1, n_in, 3) to latent_queries

**Comment by dhpitt** [comment]
Hi @alwaysbyx , we have an example with the GINO in `scripts/train_gino_carcfd.py`.

**Comment by dhpitt** [comment]
Closing as we have an example.
