### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by sinapordanesh** [neuraloperator/neuraloperator#482]
https://github.com/neuraloperator/neuraloperator/blob/202426c28fc33dc7ac61511eb9cc9cba6a8e3cbd/neuralop/training/incremental.py#L44

At this line, I'm getting an error, when initializing an IncrementalFNOTrainer object: 

`AttributeError: 'IncrementalFNOTrainer' object has no attribute 'model'`

It might better to be:
```
self.model = model
assert (isinstance(model, FNO) or isinstance(self.model, TFNO)), f"Error:... \
```

**Comment by dhpitt** [comment]
Thanks for catching this @sinapordanesh ! Fixed.
