### ISSUE TITLE
fourier_3d.py got 100+s per epoch performance on V100 16GB

### ISSUE THREAD

**Issue by PangHua** [neuraloperator/neuraloperator#57]
Hello o/,
   I am reproducing your great work! 

   But failed to find the dataset specified in fourier_3d.py file as below:
   TRAIN_PATH = 'data/ns_data_V100_N1000_T50_1.mat'
   TEST_PATH = 'data/ns_data_V100_N1000_T50_2.mat'
   
   And below is your dataset path:
   https://drive.google.com/drive/folders/1UnbQh2WWc6knEHbLn-ZaXrKUZhp7pjt-

   Let me know if I miss anything, thanks.
Hui.

**Comment by zongyi-li** [comment]
HI Hui, that is the NavierStokes_V1e-3 dataset

**Comment by PangHua** [comment]
Thanks zongyi, works now ^.^

Besides, I only got ~100+s per epoch when running the original fourier_3d.py with this NavierStokes_V1e-3 dataset, which is much slower than the result published in the paper, just to make sure I am testing on the same environment with the results.
<img width="675" alt="image" src="https://user-images.githubusercontent.com/2682285/143791417-d19fb051-f49d-4e93-bdc4-f052cdaf30b7.png">

----------------
My environment
----------------
pytorch 1.8
GPU V100 16GB
model parameters 6558537

I got ~100+s per epoch
6558537
0 104.46798364631832 0.4812950387597084 0.2651342685222626 0.14124310076236724
1 108.64541069231927 0.05057397902011871 0.09526419252157212 0.0730795532464981

Please take a look, thanks,

**Comment by zongyi-li** [comment]
Just to make sure, how many training data do you use? Is N=1000?

**Comment by PangHua** [comment]
> Just to make sure, how many training data do you use? Is N=1000?

Yes, below are some detail log.

orch.Size([1000, 64, 64, 20])
torch.Size([200, 64, 64, 20])
preprocessing finished, time used: 224.84727382846177
6558537
0 104.46798364631832 0.4812950387597084 0.2651342685222626 0.14124310076236724
1 108.64541069231927 0.05057397902011871 0.09526419252157212 0.0730795532464981
2 99.50138424150646 0.020410049008205533 0.06157019898295402 0.057365389615297316
3 99.96080369874835 0.012965587191283703 0.048911894410848616 0.046125136613845825

**Comment by zongyi-li** [comment]
It looks right to me. And what is your batchsize?

**Comment by PangHua** [comment]
> It looks right to me. And what is your batchsize?

My batchsize=10, just the original code.  The GPU seems only got lower than 10% workload...

And I am using docker on top of the V100 GPU .

**Comment by zongyi-li** [comment]
I see. It seems to be the problem of low GPU utility. Usually, the utility should be >80%.

**Comment by PangHua** [comment]
Yeah..., just to make sure, so you could got 38+s per epoch performance with batchsize=10, T=10 on the V1e-5 case?

**Comment by zongyi-li** [comment]
Right. There could be a small difference since we use the V100 32G GPU. The CPU may also play a role. But I think the main issue is GPU utility.

**Comment by PangHua** [comment]
OK，thanks.

**Comment by qxj233333** [comment]
Hello

    Your research content is very exciting, I am very interested in this
    But I have the same problem as the guy up there
    TRAIN_PATH = 'data/ns_data_V100_N1000_T50_1.mat'   =>   TRAIN_PATH = 'ns_V1e-3_N5000_T50'
    TEST_PATH = 'data/ns_data_V100_N1000_T50_2.mat'   =>   TEST_PATH = 'ns_V1e-3_N5000_T50'
    I'm a little confused as to whether this is the right approach
    
    Look forward to your reply, Thanks
    Jue

**Comment by zongyi-li** [comment]
Hello Jue,

I see your concern. As you can see in lines 173-179, we split the first `ntrain` instances for training and the last `ntest` instances for validation. As long as your `ntrain` + `ntest` < 5000, there is no data leaking. We just upload the two files in one for convenience.

Thanks,
Zongyi

**Comment by qxj233333** [comment]
Thank you for your reply

But I ran into another problem
It's about the last few lines of code

pytorch 1.10.0  Python 3.8  Cuda 11.3
GPU ：NVIDIA GeForce RTX 3090

5 0.001 100 0.5
torch.Size([1000, 64, 64, 40])
torch.Size([200, 64, 64, 40])
preprocessing finished, time used: 182.9896058999875
6558537
0 79.40636565501336 0.5612330912053585 0.3960447118282318 0.23858197689056396
1 69.98415995799587 0.1112031826749444 0.18409363317489624 0.1496196621656418
2 59.95884940199903 0.05124280059710145 0.1293589198589325 0.11953615307807923
3 43.2302961559908 0.035066749528050424 0.10697912549972534 0.10015949040651322
4 37.569226980005624 0.026436539087444543 0.0923092058300972 0.0890036779642105
Traceback (most recent call last):
  File "fourier_3d.py", line 303, in <module>
    out = y_normalizer.decode(out)
  File "/root/utilities3.py", line 99, in decode
    x = (x * std) + mean
RuntimeError: The size of tensor a (40) must match the size of tensor b (64) at non-singleton dimension 3

**Comment by zongyi-li** [comment]
Sorry, it seems to be a shape mismatch. Could you change line 302
`out = model(x)`
to
`out = model(x).view(1, S, S, T)`

Also see issue #61.

**Comment by qxj233333** [comment]
Thank you very much for your reply(By the way    Code running successfully)

**Comment by qxj233333** [comment]
something troubling(sorry to bother you)
for ns equations(v=1e-3 T=50 N=1000) 
only 20s per epoch when running the fourier_3d.py 
and the error is about 0.015 not 0.0086 in the paper

**Comment by zongyi-li** [comment]
I will try to look into the detail later this week. In the meanwhile, could you try with the original Pytorch 1.6 version? The Complex number could be unstable on some environments/devices.

**Comment by qxj233333** [comment]
I will try it

**Comment by qxj233333** [comment]
Emmm there are some errors when use Pytorch 1.6 version（about rfft）

**Comment by qxj233333** [comment]
Tesla V100S-PCIE-32GB    pytorch 1.8
ns equations(v=1e-3 T=50 N=1000)


500 0.001 100 0.5
torch.Size([1000, 64, 64, 40])
torch.Size([200, 64, 64, 40])
preprocessing finished, time used: 188.54924726858735
6558537
0 52.56507859937847 0.5527997396886348 0.3936676309108734 0.23268420457839967
1 58.87501714378595 0.11021861616522073 0.18254482984542847 0.14616583466529845



and can't reduce the error to 0.0086

**Comment by zongyi-li** [comment]
Hi Tianlin, sorry I am a bit busy at this moment. Could you try with the original Torch 1.6 implementation? It should recover the exact results. I will try to look into the new implementation later.

**Comment by JeanKossaifi** [comment]
Closing as inactive. Feel free to reopen.
