### ISSUE TITLE
Packaging and pypi ?

### ISSUE THREAD

**Issue by Forbu** [neuraloperator/neuraloperator#62]
Hello Zongyi !

I like your project / paper / code and I use it in the company I work for (It gives better result that unet, is faster and take less space ...).
I am currently repackaging (a little) your project to create a python package and I push it to pypi (to be able to make some pip install).
Do we keep your repo and I make some pull request on it or do we keep your repo intact and I use my repo as the package ? (https://github.com/Forbu/fourier_neural_operator)

**Comment by zongyi-li** [comment]
Hi Adrien, 
Glad to hear the code works well!

Yes it will be very helpful to make it a pip package, but I personally feel lazy to maintain it :sweat_smile:. How about you use your repo as the package? I am happy to advertise it on my project page.

Appreicate your help!
Zongyi

**Comment by Forbu** [comment]
Perfect ! I will try to be worthy maintainer ^^

**Comment by JeanKossaifi** [comment]
@Forbu We have a pypi package and CI now.
https://pypi.org/project/neuraloperator/

Let us know if you need anything added to the repo, best to have it all centralized so all improvements made in the model are propagated in the package!

**Comment by Forbu** [comment]
@JeanKossaifi OK I will delete it next week when I will be back from vacation!

**Comment by JeanKossaifi** [comment]
Thanks @Forbu, we can also just redirect from the mirror to the main one.
Also, feel free to open PR to make any changes to the repo!

En attendant, bonnes vacances! :)
