### ISSUE TITLE
5.5 BAYESIAN INVERSE PROBLEM 

### ISSUE THREAD

**Issue by qxj233333** [neuraloperator/neuraloperator#67]
hello, may I interrupt you for a moment
recently I want to reproduce  the application of FNO to Bayesian inverse problems (FOURIER NEURAL OPERATOR FOR
PARAMETRIC PARTIAL DIFFERENTIAL EQUATIONS section 5.5)
could you please provide some corresponding details
thanks

**Comment by JeanKossaifi** [comment]
Closing as inactive, feel free to reopen.

**Comment by zouhang0914** [comment]
> Closing as inactive, feel free to reopen.



> hello, may I interrupt you for a moment recently I want to reproduce the application of FNO to Bayesian inverse problems (FOURIER NEURAL OPERATOR FOR PARAMETRIC PARTIAL DIFFERENTIAL EQUATIONS section 5.5) could you please provide some corresponding details thanks

I also hope to get some related codes to reproduce the bayesian inverse problem. Have you solved this problem?
