### ISSUE TITLE
Padding in FNO2d breaks "super resolution"

### ISSUE THREAD

**Issue by michaepr** [neuraloperator/neuraloperator#72]
In the updated FNO2d model a 'padding' was introduced. According to a comment in the code this should help with non-periodic inputs. I think this padding may break the ability to evaluate the model on different grids than the one used for training, at least it did in my tests.

**Comment by zongyi-li** [comment]
Right, the padding number should be set with respect to the spatial domain. If I would like to pad 1/5 of the domain size, then the padding number is 10 if the domain resolution is 50; and the padding number is 20 if the domain resolution is 100.

For example, you can modify
`x = F.pad(x, [0,self.padding, 0,self.padding])`
to be 
`x = F.pad(x, [0,x.shape[-1]//5, 0,x.shape[-2]//5])`

**Comment by michaepr** [comment]
Great, thanks. Will you update the code accordingly?

**Comment by zongyi-li** [comment]
Sorry, I am a bit busy at this moment. But I will update it in the next version.

**Comment by michaepr** [comment]
Ok, then I'll keep the issue open until it's included in the code

**Comment by BraveDrXuTF** [comment]
Could I ask questions about padding?
What's the intuition of the padding operation? I don't know why it is connected to non-periodic condition, and I'm confused about it.
Thanks.

**Comment by BraveDrXuTF** [comment]
And the padding doesn't seem to appear in the paper.

**Comment by zongyi-li** [comment]
Sorry for the delay. The idea of padding is to put the input domain into a larger padded domain which is periodic. In this case, the Fourier series is defined on the padded periodic domain.

**Comment by JeanKossaifi** [comment]
Domain padding is fixed in the latest version, see https://neuraloperator.github.io/neuraloperator/dev/modules/generated/neuralop.models.padding.DomainPadding.html#neuralop.models.padding.DomainPadding
