### ISSUE TITLE
How to train in several GPUs?

### ISSUE THREAD

**Issue by Sakurapola** [neuraloperator/neuraloperator#88]
Hi, thans to your excellent work! I meet some problems when trying to train in 8 GPUS, one of the operations goes wrong. It returns:RuntimeError: einsum(): the number of subscripts in the equation (5) does not match the number of dimensions (6) for operand 1 and no ellipsis was given. But the situation disappears when I turn to single GPU. Hope to get some answers from you to clear my confusion！

**Comment by zongyi-li** [comment]
one possible issue is that pytorch data parallel does not support complex parameters. An. easy fix is to use real parameters and convert them to complex in the multiplication
`self.weights1 = nn.Parameter(self.scale * torch.rand(in_channels, out_channels, self.modes1, self.modes2, dtype=torch.cfloat))` becomes
`self.weights1 = nn.Parameter(self.scale * torch.rand(in_channels, out_channels, self.modes1, self.modes2, 2, dtype=torch.float))`

and in forward pass
`self.compl_mul2d(x_ft[:, :, :self.modes1, :self.modes2], torch.view_as_complex(self.weights1))`

**Comment by Sakurapola** [comment]
if I use fno_3d.py then turn weights channels to 3 and pass self.compl_mul3d? If so, what will change to torch.fft.rfftn(x_ft)?

**Comment by zongyi-li** [comment]
fno_3d still has channel 2, which is the real channel and complex channel. 3d has three modes: self.modes1, self.modes2, self.modes3. You don't need to change torch.fft.rfftn(x_ft).

You may also use the AFNO implementation https://github.com/NVlabs/AFNO-transformer/blob/master/afno/afno2d.py

**Comment by JeanKossaifi** [comment]
We have DDP out-of the box now
