### ISSUE TITLE
plot the solution of the Burgers equation at any time t.

### ISSUE THREAD

**Issue by fateminem21** [neuraloperator/neuraloperator#90]
Hi, I want to plot the solution of the Burgers equation at any time t predicted by fourier_1d.py.
So I wrote the following code, but when I run it, the prediction results remain constant and nothing changes.
```
with torch.no_grad():
    for i, (x, y) in enumerate(test_loader):
        x, y = x.cuda(), y.cuda()

        out = model(x)
        
        y_values = y.cpu().numpy()
        out_values = out.cpu().numpy()
        plt.clf()
        plt.plot(out_values[i])
        plt.plot(y_values[i])
        plt.show()
```
![image_0](https://user-images.githubusercontent.com/120445802/207243733-eed7839f-bf91-4b86-a6cb-05d50ea05c6d.png)
By plotting each of Prediction and Grand Truth separately, I noticed that the vertical scale of the images is different.

Grand Truth
![image](https://user-images.githubusercontent.com/120445802/207246115-2b5e07c8-5bf9-479a-bc13-f9fa2955dcb4.png)

Prediction
![image](https://user-images.githubusercontent.com/120445802/207246148-65947f8b-d6bd-4f15-891e-fb98d9faba05.png)
All results are at t=0. However, looking at the Grand Truth and Prediction results, it appears that no inference has been made.        
I have done only 10 epochs of learning, so is there a large margin of error and am I getting results that would change the scale?

Or are there other areas where I am wrong?
There are two lines of code for inference, [line 196](https://github.com/zongyi-li/fourier_neural_operator/blob/da9cfef310662fe7c68b52e7c03fde5166088463/fourier_1d.py#L196) and [line 214](https://github.com/zongyi-li/fourier_neural_operator/blob/da9cfef310662fe7c68b52e7c03fde5166088463/fourier_1d.py#L214), I followed [this issue](https://github.com/zongyi-li/fourier_neural_operator/issues/82#issuecomment-1344072039) and used the inference code on line 196. Could this be the cause?
Can someone please clear up my confusion?

Dataset
Burgers_v100

**Comment by zongyi-li** [comment]
Hmm, what are `out_values[I]` and` y_values[I]`? Could you directly plot `out.cpu().numpy()` and `y.cpu().numpy()`? 

And what is the testing error at 10 epochs?

**Comment by Sh1gechan** [comment]
I have a similar question.
I tried to plot the burgers1D variation up to T=100 in the burgers_v100_t100_r1024_N2048.mat dataset, but the uploaded code does not work.
More specifically, I am trying to plot something like the Burgers Equation 1D gif in the ReadMe of the following repository.
https://github.com/shawnrosofsky/PINO_Applications
I also saw a discussion about doing something similar on another [issue](https://github.com/neural-operator/fourier_neural_operator/issues/68). From what is being discussed here, I infer that to learn and infer the time-dependent Burgers Equation 1D, all I need to do is change the class SpectralConv2d to SpectralConv1d and FNO2d to FNO1d in fourier_2d_time.py?

Then again, what I write below is speculation.
Perhaps @fateminem21  is trying to plot the elapsed time from t=0 to t=100 in fourier_1d.py, but fourier_1d.py is time-independent. Therefore, it would be difficult to plot the time passage with fourier_1d.py.
Also, when I rewrote only the inference code of fourier_1d.py on github to that of fateminem21, the test error was 0.023543993756175042, which is less than 0.05, so I assume that the learning is going well.

**Comment by fateminem21** [comment]
@zongyi-li 
Sorry for the delay in replying.
And @Sh1gechan thank you for your message.
I was mistaken. fourier_1d.py is time-independent, is it not?
The y.cpu().numpy() and out.cpu().numpy() are
(batchsize, image size) of (20,128).
It seems that I was plotting something irrelevant to the passage of time because I assumed it to be the i-th of (batchsize, image size).
So how do I plot the time-dependent burgers equation 1D?
Specifically, which architecture should I use for predicting? Also, are there any special config,load data settings like other python scripts?
such as
sub = 2**3
h = 2**13

First of all, am I correct in understanding that t100 in the burgers_v100_t100_r1024_N2048.mat dataset published in PDE datasets is a dataset that records the time passage from t=0 to t=100?
As mentioned in [this issue](https://github.com/neural-operator/fourier_neural_operator/issues/68), I tried rewriting spectralconv2d and FNO2d in fourier_2d_time.py to spectralconv1d and FNO1d respectively, but I could not get it to work because I did not understand how to set config and load data. 
I apologize for the inconvenience, but I would appreciate your help.

**Comment by zongyi-li** [comment]
Sorry for the delayed response.
fourier_1d is designed for time-independent problems. For example, mapping from the solution at t=0 to t=1. So it only has the spatial dimension.
burgers_v100_t100_r1024_N2048.mat is the burgers equation with space and time. So it's better to use fourier_2d that does convolution in two dimensions.

**Comment by fateminem21** [comment]
@zongyi-li 
Thanks for the reply.
When using fourier_2d.py, there doesn't seem to be a place to set the time, where can I change it?
For example, if I want to predict from t=0 to t=100, the shape of the dataset would probably be something like ```[batchsize, s, T]```, where should I set T?
Also, I don't think simply changing the train path and test path in fourier_2d.py to burgers_v100_t100_r1024_N2048.mat will work.

**Comment by zongyi-li** [comment]
Hi @fateminem21 , for the time-dependent problem like Burger(with time) and NS, we have two formulation (1) auto-regressive map G:u[t] -> u[t+1] or (2) spatial-temporal convolution G:u[0] -> u[1:T]. For the second setting we have an example of 2d+time NS in `fourier_3d.py` https://github.com/neuraloperator/neuraloperator/blob/master/fourier_3d.py#L192 . You take a look how we load the time-dependent data. Since Burger is 1d+time, you can do the same formulation with `fourier_2d.py`.
