### ISSUE TITLE
Explanation of Navier Stokes data

### ISSUE THREAD

**Issue by ShikharShivraj** [neuraloperator/neuraloperator#98]
Hello, I am using the file in "NavierStokes_V1e-3_N5000_T50.mat" to fit a model on the Navier-Stokes equation data. I had a query regarding what each field represents and how the data is oriented. 

I understand that 't' is the time step, and I presumed 'a' are the grid points because the shape is (64, 64), and 'u' is the vorticity data at every grid point, at every timestep, for every training sample. My confusion is thus - assuming 'a' represents the 64 * 64 grid, shouldn't the value in a[i][j] be a tuple of (x,y) representing coordinates? Is my understanding correct? I also assumed that the grid points are different for every sample and hence 'a' is of the shape 64*64*5000. Is that right?

**Comment by zongyi-li** [comment]
Hi, For the time-dependent problem like NS, we have two formulation (1) auto-regressive map G:u[t] -> u[t+1] or (2) spatial-temporal convolution G:u[0] -> u[1:T]. I guess you mean the input `a` is u[t].

**Comment by ShikharShivraj** [comment]
Which dataset (let's say we don't care about viscoscity) is better to learn the mapping from u[0:t] to value of u at a given T, so u[T]. I currently used "NavierStokes_V1e-3_N5000_T50.mat". From your comment, I think I used an incorrect dataset?

**Comment by zongyi-li** [comment]
Sorry for the delay! Yes  "NavierStokes_V1e-3_N5000_T50.mat" is the good one to learn the mapping from u[0:t] to u[T].  The input will be the shape of (batch 64, 64, t). The output will be the shape of (batch, 64, 64, 1). You can use the fourier_2d code https://github.com/neuraloperator/neuraloperator/blob/master/fourier_2d.py and set the input and output as u[0:t] and u[T].
