### ISSUE TITLE
What config to use to test training on small darcy data?

### ISSUE THREAD

**Issue by dlvp** [neuraloperator/neuraloperator#99]
I'm trying to test the `darcy_train` script on the small datasets `data/darcy_*.pt`.

I replaced `load_darcy_pt` [here](https://github.com/neuraloperator/neuraloperator/blob/60b5dbd0935abc2543c9973c62212a03d90b2494/scripts/train_darcy.py#L58) with  [this](https://github.com/neuraloperator/neuraloperator/blob/60b5dbd0935abc2543c9973c62212a03d90b2494/neuralop/datasets/darcy.py#L9) and changed the test and train resolution in `darcy_config.yaml`.

However I'm getting an error:
```python
Traceback (most recent call last):
  File "/job/.local/lib/python3.8/site-packages/tensorly/plugins.py", line 72, in cached_einsum
    expression = OPT_EINSUM_PATH_CACHE[key]
KeyError: 'abcd,becd->aecd,(16, 64, 17, 9),(64, 64, 32, 32)'
```
from
```python
  File "/job/.local/lib/python3.8/site-packages/neuralop/models/fno_block.py", line 383, in forward
    out_fft[:, :, :self.half_modes_height, :self.half_modes_width] = self._contract(x[:, :, :self.half_modes_height, :self.half_modes_width], 
  File "/job/.local/lib/python3.8/site-packages/neuralop/models/fno_block.py", line 36, in _contract_dense
    return tl.einsum(eq, x, weight)
```
Are there further changes i need ot apply to the config to run this simple test?

**Comment by JeanKossaifi** [comment]
I think it's because the training resolution is only 16 but you're trying to use 32 modes in the Fourier domain. I updated the default config, that should fix your issue.

**Comment by JeanKossaifi** [comment]
@dlvp did this fix your issue?

**Comment by dlvp** [comment]
It did! Thank you so much.

**Comment by JeanKossaifi** [comment]
Glad to hear! Closing the issue.
